services:

    _defaults:
        autowire: true
        public:   false

    perf\Vc\:
        resource: '../src/*'

    perf\Vc\Controller\ControllerClassResolverInterface:
        class: perf\Vc\Controller\ControllerClassResolver

    perf\Vc\Controller\ControllerFactoryInterface:
        class: perf\Vc\Controller\ControllerFactory

    perf\Vc\FrontControllerInterface:
        class: perf\Vc\FrontController

    perf\Vc\Redirection\RedirectionHeadersGeneratorInterface:
        class: perf\Vc\Redirection\RedirectionHeadersGenerator

    perf\Vc\Redirection\RedirectionResponseGeneratorInterface:
        class: perf\Vc\Redirection\RedirectionResponseGenerator

    perf\Vc\Request\RequestInterface:
        factory: ['@perf\Vc\Request\RequestPopulatorInterface', 'populate']

    perf\Vc\Request\RequestPopulatorInterface:
        factory: [perf\Vc\Request\RequestPopulator, createDefault]

    perf\Vc\Response\ResponseBuilderFactoryInterface:
        class: perf\Vc\Response\ResponseBuilderFactory

    perf\Vc\Response\ResponseSenderInterface:
        class: perf\Vc\Response\ResponseSender

    perf\Vc\Routing\RouteGeneratorInterface:
        class: perf\Vc\Routing\RouteGenerator

    perf\Vc\Routing\RouterInterface:
        class: perf\Vc\Routing\Router

    perf\Vc\Routing\RoutingRuleImporterInterface:
        class: perf\Vc\Routing\YamlRoutingRuleImporter

    perf\Vc\Routing\RoutingRuleMatcherInterface:
        class: perf\Vc\Routing\RoutingRuleMatcher

    perf\Vc\Response\Transformation\TransformerRepositoryInterface:
        factory: [perf\Vc\Response\Transformation\TransformerRepository, createDefault]

    perf\Vc\View\ViewLocatorInterface:
        class: perf\Vc\View\ViewLocator

    perf\Vc\View\ViewRendererInterface:
        class: perf\Vc\View\TwigViewRenderer

    perf\Vc\VcRunner:
        public: true

    # External dependencies

    perf\Caching\Storage\CachingStorageInterface:
        class: perf\Caching\Storage\VolatileCachingStorage

    perf\HttpStatus\HttpStatusRepositoryInterface:
        factory: [perf\HttpStatus\HttpStatusRepository, createDefault]

    perf\Timing\ClockInterface:
        class: perf\Timing\Clock

    Twig\Cache\CacheInterface:
        class: perf\Vc\View\TwigCache
